"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { persistor, store } from '../Redux/store'
import { Provider } from 'react-redux'
import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Bonvo Exports",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Bonvo Exports</title>
        <meta name='description' content='Description' />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>

            <Navbar />
            {children}
          </PersistGate>

        </Provider>
      </body>
    </html>
  );
}
